/* Observation–State Correlation Explorer
   Web port of notebook 1.step_by_step_with_vort2d_case.ipynb, §
   "Visualize the error distribution and correlation" (plot_corr_map).

   Single-variable teaching version: one temperature field T, one
   observation of T, ensemble = truth + smooth correlated perturbations.
   The correlation map is a clean blob centred on the observation that
   decays with distance.

   Data: window.NEDAS_DATA (generated by generate_data.py).
*/
(function () {
  "use strict";

  const D = window.NEDAS_DATA;
  if (!D) {
    document.body.innerHTML = "<p style='font:1rem sans-serif;padding:2rem'>" +
      "No data found. Run <code>python generate_data.py</code> to create <code>data.js</code>.</p>";
    return;
  }

  const $ = (id) => document.getElementById(id);
  const nx = D.meta.nx, ny = D.meta.ny, nens = D.meta.nens;
  const xM = D.x, yM = D.y;                  // grid cell centers, m
  const truthT = D.truth.T;                  // [j][i]
  const corrT = D.corr.T;                    // [j][i]
  const ensT = D.ens.T;                      // [j][i][m]
  const obsEns = D.obs_ens;                  // [m]
  const obs = D.obs;                         // {i,j,x,y,val}
  const kx = nx - 1, ky = ny - 1;

  // ------------------------------------------------------------- theme
  // Follows the browser's light/dark preference (no manual toggle in the
  // embedded layout).
  const darkMq = window.matchMedia("(prefers-color-scheme: dark)");
  let theme = darkMq.matches ? "dark" : "light";
  // when embedded in a site page the widget lives inside a .da-widget wrapper,
  // which carries the CSS custom properties and the data-theme attribute;
  // standalone (file://) it falls back to the document root.
  const root = document.querySelector(".da-widget") || document.documentElement;
  const setTheme = (t) => { theme = t; root.dataset.theme = t; render(); };
  darkMq.addEventListener("change", (e) => setTheme(e.matches ? "dark" : "light"));

  const cssVar = (n) => getComputedStyle(root).getPropertyValue(n).trim();

  // ------------------------------------------- diverging colour ramp LUT
  // blue ↔ neutral ↔ red (dataviz diverging pair; midpoint = surface)
  const LUT_STOPS = {
    light: [
      [-1.0, "#104281"], [-0.5, "#2a78d6"], [-0.15, "#cde2fb"],
      [0.0, "#f0efec"],
      [0.15, "#f6c6b6"], [0.5, "#e34948"], [1.0, "#a52828"],
    ],
    dark: [
      [-1.0, "#3987e5"], [-0.5, "#6da7ec"], [-0.15, "#454b61"],
      [0.0, "#383835"],
      [0.15, "#5b443d"], [0.5, "#e66767"], [1.0, "#b93636"],
    ],
  };

  function hex2rgb(h) {
    return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
  }
  function makeLUT(stops) {
    const lut = new Array(256);
    for (let k = 0; k < 256; k++) {
      const t = k / 255;               // 0..1 across field range
      const v = t * 2 - 1;             // -1..1
      let s = 0;
      while (s < stops.length - 2 && v > stops[s + 1][0]) s++;
      const [v0, c0] = stops[s], [v1, c1] = stops[s + 1];
      const f = (v - v0) / (v1 - v0 || 1);
      const a = hex2rgb(c0), b = hex2rgb(c1);
      lut[k] = [a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f, a[2] + (b[2] - a[2]) * f];
    }
    return lut;
  }
  const lut = makeLUT(LUT_STOPS.light);

  // ----------------------------------------------------------- ranges
  // truth range (symmetric, rounded to a whole K)
  let rmax = 0;
  for (let j = 0; j < ny; j++)
    for (let i = 0; i < nx; i++)
      rmax = Math.max(rmax, Math.abs(truthT[j][i]));
  const vmax = Math.ceil(rmax);

  // scatter range: fixed once from all ensemble values, so axes stay stable
  let smax = Math.abs(obsEns[0]);
  for (let j = 0; j < ny; j++) {
    for (let i = 0; i < nx; i++) {
      const row = ensT[j][i];
      for (let m = 0; m < nens; m++) smax = Math.max(smax, Math.abs(row[m]));
    }
  }
  const srange = Math.ceil(smax * 1.05 / 5) * 5;

  // ----------------------------------------------------------- state
  let si = 9, sj = 26;                  // (i, j) of the state marker (far-side anti-correlated lobe)
  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

  // ------------------------------------------------------ canvas utils
  function fitCanvas(cv) {
    const rect = cv.getBoundingClientRect();
    const dpr = window.devicePixelRatio || 1;
    const w = Math.max(1, Math.round(rect.width * dpr));
    const h = Math.max(1, Math.round(rect.height * dpr));
    if (cv.width !== w || cv.height !== h) { cv.width = w; cv.height = h; }
    const ctx = cv.getContext("2d");
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, rect.width, rect.height);
    return { ctx, w: rect.width, h: rect.height };
  }

  function drawField(ctx, W, H, field, lo, hi) {
    const off = document.createElement("canvas");
    off.width = nx; off.height = ny;
    const octx = off.getContext("2d");
    const img = octx.createImageData(nx, ny);
    const data = img.data;
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const t = clamp((field[j][i] - lo) / (hi - lo || 1), 0, 1);
        const c = lut[Math.round(t * 255)];
        const p = (j * nx + i) * 4;
        data[p] = c[0]; data[p + 1] = c[1]; data[p + 2] = c[2]; data[p + 3] = 255;
      }
    }
    octx.putImageData(img, 0, 0);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(off, 0, 0, W, H);
  }

  function px(i) { return (i + 0.5) / nx; }   // normalised 0..1
  function py(j) { return (j + 0.5) / ny; }

  function drawMarkers(ctx, W, H) {
    const cx = cssVar("--accent-fill");
    // obs marker: red circle, white face (notebook add_obs_marker)
    const ox = px(obs.i) * W, oy = py(obs.j) * H;
    ctx.beginPath();
    ctx.arc(ox, oy, 7, 0, Math.PI * 2);
    ctx.fillStyle = cx; ctx.fill();
    ctx.lineWidth = 1.75;
    ctx.strokeStyle = cssVar("--series-red");
    ctx.stroke();
    // state marker: black square, white face (notebook add_state_marker)
    const sx = px(si) * W, sy = py(sj) * H, s = 6;
    ctx.fillStyle = cx;
    ctx.fillRect(sx - s, sy - s, s * 2, s * 2);
    ctx.lineWidth = 1.75;
    ctx.strokeStyle = cssVar("--series-ink");
    ctx.strokeRect(sx - s, sy - s, s * 2, s * 2);
  }

  // axis ticks on maps (km, centred on domain, like notebook set_map_axis)
  function drawMapAxis(ctx, W, H) {
    const ink = cssVar("--ink-3");
    ctx.font = "9px system-ui, sans-serif";
    ctx.fillStyle = ink;
    const cticks = [5, 15, 25, 35, 45];
    for (const c of cticks) {
      const xpos = px(c) * W;
      ctx.beginPath();
      ctx.moveTo(xpos, H - 1); ctx.lineTo(xpos, H - 4);
      ctx.strokeStyle = ink; ctx.lineWidth = 1; ctx.stroke();
      const lab = Math.round((xM[c] - D.meta.Lx / 2) / 1e3);
      ctx.textAlign = "center";
      ctx.fillText(lab, xpos, H - 6);
      const ypos = py(c) * H;
      ctx.beginPath();
      ctx.moveTo(0, ypos); ctx.lineTo(4, ypos);
      ctx.strokeStyle = ink; ctx.stroke();
      ctx.textAlign = "left";
      ctx.fillText(Math.round((yM[c] - D.meta.Ly / 2) / 1e3), 6, ypos + 3);
    }
  }

  function drawColorbar(cv, lo, hi) {
    const { ctx, w, h } = fitCanvas(cv);
    for (let k = 0; k < w; k++) {
      const c = lut[Math.round((k / (w - 1)) * 255)];
      ctx.fillStyle = `rgb(${c[0] | 0},${c[1] | 0},${c[2] | 0})`;
      ctx.fillRect(k, 0, 1, h);
    }
    const lbl = cv.parentElement.querySelector(".cb-labels");
    if (lbl) {
      const f = (x) => (Math.abs(x) < 1e-9 ? "0" : x.toFixed(x < 3 ? 1 : 0));
      lbl.querySelector(".cb-min").textContent = f(lo);
      lbl.querySelector(".cb-mid").textContent = "0";
      lbl.querySelector(".cb-max").textContent = f(hi);
    }
  }

  // ------------------------------------------------------------ scatter
  function drawScatter(cv, ensVals, truthVal, r, vname) {
    const { ctx, w, h } = fitCanvas(cv);
    const mL = 40, mR = 12, mT = 10, mB = 30;
    const pw = w - mL - mR, ph = h - mT - mB;
    const X = (v) => mL + ((v + srange) / (2 * srange)) * pw;
    const Y = (v) => mT + ((srange - v) / (2 * srange)) * ph;

    // axes + grid
    ctx.strokeStyle = cssVar("--line");
    ctx.lineWidth = 1;
    for (const t of [-srange, -srange / 2, 0, srange / 2, srange]) {
      ctx.beginPath(); ctx.moveTo(X(t), mT); ctx.lineTo(X(t), mT + ph); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(mL, Y(t)); ctx.lineTo(mL + pw, Y(t)); ctx.stroke();
    }
    ctx.strokeStyle = cssVar("--axis");
    ctx.strokeRect(mL, mT, pw, ph);

    // tick labels
    ctx.font = "9px system-ui, sans-serif";
    ctx.fillStyle = cssVar("--ink-3");
    ctx.textAlign = "center";
    for (const t of [-srange, 0, srange]) {
      ctx.fillText(Math.round(t), X(t), mT + ph + 12);
      ctx.fillText(Math.round(t), mL - 5, Y(t) + 3);
    }
    ctx.textAlign = "center";
    ctx.fillStyle = cssVar("--ink-2");
    ctx.fillText(`Obs T (K)`, mL + pw / 2, h - 6);
    ctx.save();
    ctx.translate(12, mT + ph / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.fillText(`State T (K)`, 0, 0);
    ctx.restore();

    // ensemble points (aqua)
    ctx.fillStyle = cssVar("--series-aqua");
    for (let m = 0; m < nens; m++) {
      ctx.globalAlpha = 0.75;
      ctx.beginPath();
      ctx.arc(X(obsEns[m]), Y(ensVals[m]), 2.4, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.globalAlpha = 1;

    // observation value line (amber) at x = obs.val
    ctx.strokeStyle = cssVar("--series-amber");
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(X(obs.val), mT);
    ctx.lineTo(X(obs.val), mT + ph);
    ctx.stroke();

    // truth value line (ink) at y = truth at (i,j)
    ctx.strokeStyle = cssVar("--series-ink");
    ctx.lineWidth = 1.25;
    ctx.beginPath();
    ctx.moveTo(mL, Y(truthVal));
    ctx.lineTo(mL + pw, Y(truthVal));
    ctx.stroke();
  }

  // ------------------------------------------------------------- render
  function render() {
    // re-build LUT for current theme
    const stops = LUT_STOPS[theme];
    const l2 = makeLUT(stops);
    lut.splice(0, lut.length, ...l2);

    // truth / corr maps
    drawMap($("map-truth"), truthT, -vmax, vmax);
    drawMap($("map-corr"), corrT, -1, 1);
    drawColorbar($("cb-truth"), -vmax, vmax);
    drawColorbar($("cb-corr"), -1, 1);

    // scatter panel
    const r = corrT[sj][si];
    drawScatter($("scat"), ensT[sj][si], truthT[sj][si], r, "T");
    $("t-scat").textContent = "r = " + r.toFixed(2);

    // sliders + readout
    $("islider").value = si;
    $("jslider").value = sj;
    $("i-val").textContent = si;
    $("j-val").textContent = sj;
    $("readout").innerHTML =
      `State <strong>(i, j) = (${si}, ${sj})</strong> · ` +
      `truth T = <strong>${truthT[sj][si].toFixed(1)}</strong> K · ` +
      `corr(obs T, state T) = <strong>${r.toFixed(2)}</strong>`;
  }

  function drawMap(cv, field, lo, hi) {
    const { ctx, w, h } = fitCanvas(cv);
    drawField(ctx, w, h, field, lo, hi);
    drawMarkers(ctx, w, h);
    drawMapAxis(ctx, w, h);
  }

  // --------------------------------------------------------- interaction
  function mapPosToIJ(cv, clientX, clientY) {
    const rect = cv.getBoundingClientRect();
    const fx = clamp((clientX - rect.left) / rect.width, 0, 1);
    const fy = clamp((clientY - rect.top) / rect.height, 0, 1);
    return { i: Math.floor(fx * nx), j: Math.floor(fy * ny) };
  }

  function setMarker(i, j, doRender) {
    si = clamp(Math.round(i), 0, kx);
    sj = clamp(Math.round(j), 0, ky);
    if (doRender !== false) render();
  }

  // click / drag on any map to move the state marker
  for (const id of ["map-truth", "map-corr"]) {
    const cv = $(id);
    let dragging = false;
    const move = (e) => {
      const { i, j } = mapPosToIJ(cv, e.clientX, e.clientY);
      if (dragging || e.type === "click") setMarker(i, j, true);
    };
    cv.addEventListener("pointerdown", (e) => { dragging = true; move(e); cv.setPointerCapture(e.pointerId); });
    cv.addEventListener("pointermove", (e) => { if (dragging) move(e); });
    cv.addEventListener("pointerup", () => { dragging = false; });
    // hover tooltip
    cv.addEventListener("pointermove", (e) => {
      const { i, j } = mapPosToIJ(cv, e.clientX, e.clientY);
      showTooltip(e.clientX, e.clientY, i, j);
    });
    cv.addEventListener("pointerleave", hideTooltip);
  }

  // tooltip: value at the hovered cell
  let tip = document.createElement("div");
  tip.id = "tooltip";
  (root || document.body).appendChild(tip);
  function showTooltip(cx, cy, i, j) {
    tip.innerHTML =
      `<strong>(${i}, ${j})</strong>` +
      ` · T = ${truthT[j][i].toFixed(2)} K` +
      ` · corr = ${corrT[j][i].toFixed(2)}`;
    tip.style.display = "block";
    const pad = 14;
    let lx = cx + pad, ly = cy + pad;
    if (lx + 240 > window.innerWidth) lx = cx - 260;
    if (ly + 30 > window.innerHeight) ly = cy - 40;
    tip.style.left = lx + "px";
    tip.style.top = ly + "px";
  }
  function hideTooltip() { tip.style.display = "none"; }

  $("islider").addEventListener("input", (e) => setMarker(parseInt(e.target.value, 10), sj, true));
  $("jslider").addEventListener("input", (e) => setMarker(si, parseInt(e.target.value, 10), true));

  window.addEventListener("resize", () => render());
  // re-render when the embedded widget's box changes size (e.g. the site page
  // reflows while fonts/images load); a no-op in the standalone layout.
  if (window.ResizeObserver) new ResizeObserver(() => render()).observe(root);

  // ----------------------------------------------------------------- init
  const nensEl = $("nens-label");   // optional: shown in the standalone hero tag
  if (nensEl) nensEl.textContent = nens;
  $("islider").min = 0; $("islider").max = kx;
  $("jslider").min = 0; $("jslider").max = ky;
  setTheme(theme);   // sets data-theme + first render
})();
