// © Yue Ying, CC BY 4.0 — https://myying.github.io/pages/software/2026.DA.short.tutorial/toc.html
/* Observation–State Correlation Explorer
   Web port of notebook 1.step_by_step_with_vort2d_case.ipynb, §
   "Visualize the error distribution and correlation" (plot_corr_map).

   Single-variable teaching version: one temperature field T, one
   observation of T, ensemble = truth + smooth correlated perturbations.
   The correlation map is a clean blob centred on the observation that
   decays with distance.

   Panel 1 also shows the ensemble's 4 K contours (truth + all members,
   marching-squares extraction) with a member slider: the selected member's
   ring lights up, its blob centre is marked, and its point is ringed in
   the scatter — the position uncertainty that drives the correlation.

   Data: window.NEDAS_DATA (generated by generate_data.py).
*/
(function () {
  "use strict";

  const D = window.NEDAS_DATA;
  if (!D) {
    document.body.innerHTML = "<p style='font:1rem sans-serif;padding:2rem'>" +
      "No data found. Run <code>python generate_data.py</code> to create <code>data.js</code>.</p>";
    return;
  }

  const $ = (id) => document.getElementById(id);
  const nx = D.meta.nx, ny = D.meta.ny, nens = D.meta.nens;
  const xM = D.x, yM = D.y;                  // grid cell centers, m
  const truthT = D.truth.T;                  // [j][i]
  const corrT = D.corr.T;                    // [j][i]
  const ensT = D.ens.T;                      // [j][i][m]
  const obsEns = D.obs_ens;                  // [m]
  const obs = D.obs;                         // {i,j,x,y,val}
  const kx = nx - 1, ky = ny - 1;
  const LKM = D.meta.Lx / 1e3;             // domain width, km

  // ------------------------------------------- covariance = std_x·std_y·corr
  // corrT (from data.js) is Corr(Obs T, State T) at every grid point. The
  // ensemble std of the observed variable is a single number (obs location is
  // fixed); the ensemble std of the state varies by grid point. Multiplying
  // corr by both stds turns the correlation map into a covariance map — the
  // quantity the Kalman gain actually uses (K = Cov / (Var_state_obs + Var_o)).
  function stdOf(arr) {
    let s = 0;
    for (let m = 0; m < arr.length; m++) s += arr[m];
    const mean = s / arr.length;
    let v = 0;
    for (let m = 0; m < arr.length; m++) v += (arr[m] - mean) * (arr[m] - mean);
    return Math.sqrt(v / arr.length);
  }
  const stdObs = stdOf(obsEns);
  const stdState = new Array(ny);
  const covT = new Array(ny);
  for (let j = 0; j < ny; j++) {
    stdState[j] = new Array(nx);
    covT[j] = new Array(nx);
    for (let i = 0; i < nx; i++) {
      stdState[j][i] = stdOf(ensT[j][i]);
      covT[j][i] = corrT[j][i] * stdObs * stdState[j][i];
    }
  }
  let covmax = 0;
  for (let j = 0; j < ny; j++)
    for (let i = 0; i < nx; i++)
      covmax = Math.max(covmax, Math.abs(covT[j][i]));
  covmax = Math.max(0.1, Math.ceil(covmax * 10) / 10);   // round up to 0.1 K²

  // ------------------------------------------------------------- theme
  // Follows the browser's light/dark preference (no manual toggle in the
  // embedded layout).
  const darkMq = window.matchMedia("(prefers-color-scheme: dark)");
  let theme = darkMq.matches ? "dark" : "light";
  // when embedded in a site page the widget lives inside a .da-widget wrapper,
  // which carries the CSS custom properties and the data-theme attribute;
  // standalone (file://) it falls back to the document root. Target the own
  // wrapper id so the widget binds to its own root even if another widget
  // shares the page.
  const root = document.getElementById("corr-explorer") ||
    document.querySelector(".da-widget") || document.documentElement;
  const setTheme = (t) => { theme = t; root.dataset.theme = t; render(); };
  darkMq.addEventListener("change", (e) => setTheme(e.matches ? "dark" : "light"));

  const cssVar = (n) => getComputedStyle(root).getPropertyValue(n).trim();

  // ------------------------------------------- diverging colour ramp LUT
  // blue ↔ neutral ↔ red (dataviz diverging pair; midpoint = surface)
  const LUT_STOPS = {
    light: [
      [-1.0, "#104281"], [-0.5, "#2a78d6"], [-0.15, "#cde2fb"],
      [0.0, "#f0efec"],
      [0.15, "#f6c6b6"], [0.5, "#e34948"], [1.0, "#a52828"],
    ],
    dark: [
      [-1.0, "#3987e5"], [-0.5, "#6da7ec"], [-0.15, "#454b61"],
      [0.0, "#383835"],
      [0.15, "#5b443d"], [0.5, "#e66767"], [1.0, "#b93636"],
    ],
  };

  // sequential truth-field ramp, same as the Ch. 6 covariance explorer:
  // YlOrRd (ColorBrewer) in light mode, bright thermal in dark mode
  const LUT_THERMAL = {
    light: [
      [0.000, "#ffffcc"], [0.125, "#ffeda0"], [0.250, "#fed976"], [0.375, "#feb24c"],
      [0.500, "#fd8d3c"], [0.625, "#fc4e2a"], [0.750, "#e31a1c"], [0.875, "#bd0026"],
      [1.000, "#800026"],
    ],
    dark: [
      [0.0, "#241439"], [0.18, "#4a1a7d"], [0.38, "#8d218f"], [0.55, "#d23570"],
      [0.72, "#f9702f"], [0.86, "#ffb94d"], [0.95, "#fff0a0"], [1.0, "#ffffff"],
    ],
  };

  function hex2rgb(h) {
    return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
  }
  // generic 256-entry LUT; `map` turns the field fraction t (0..1) into the
  // stops' domain: diverging uses v = 2t−1, sequential uses v = t
  function makeLUT(stops, map) {
    const lut = new Array(256);
    for (let k = 0; k < 256; k++) {
      const v = map(k / 255);
      let s = 0;
      while (s < stops.length - 2 && v > stops[s + 1][0]) s++;
      const [v0, c0] = stops[s], [v1, c1] = stops[s + 1];
      const f = (v - v0) / (v1 - v0 || 1);
      const a = hex2rgb(c0), b = hex2rgb(c1);
      lut[k] = [a[0] + (b[0] - a[0]) * f, a[1] + (b[1] - a[1]) * f, a[2] + (b[2] - a[2]) * f];
    }
    return lut;
  }
  const divMap = (t) => t * 2 - 1;
  const seqMap = (t) => t;
  const lut = makeLUT(LUT_STOPS.light, divMap);       // diverging: correlation
  const lutTh = makeLUT(LUT_THERMAL.light, seqMap);   // sequential: truth

  // ----------------------------------------------------------- ranges
  // truth range (symmetric, rounded to a whole K)
  let rmax = 0;
  for (let j = 0; j < ny; j++)
    for (let i = 0; i < nx; i++)
      rmax = Math.max(rmax, Math.abs(truthT[j][i]));
  const vmax = Math.ceil(rmax);

  // scatter range: a fixed window [-2, 10] K — every state and observation
  // value lies in [0, 8] (the truth blob peaks at ~7.9 K), so the axes stay
  // stable and the cloud fills the plot (zoomed compared with the full range)
  const S_LO = -2, S_HI = 10;
  const SC_M = { l: 40, r: 12, t: 10, b: 30 };   // scatter plot margins (CSS px)

  // ----------------------------------------------------------- state
  let si = 33, sj = 18;                  // (i, j) of the state marker
  let sel = 49;                          // selected member, 0-based (default #50)
  let showContours = true;               // show member contours in the truth map panel
  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

  // ------------------------------ 4 K contour extraction (marching squares)
  // The 4 K contour (LEVEL, K) of a flat field (value at j*nx+i), returned as
  // segments in normalised map coordinates (0..1).
  const LEVEL = 4.0;
  function contourSegs(field) {
    const segs = [];
    for (let j = 0; j < ny - 1; j++) {
      for (let i = 0; i < nx - 1; i++) {
        const v = [field[j * nx + i] - LEVEL, field[j * nx + i + 1] - LEVEL,
                   field[(j + 1) * nx + i + 1] - LEVEL, field[(j + 1) * nx + i] - LEVEL];
        let mask = 0;
        for (let k = 0; k < 4; k++) if (v[k] >= 0) mask |= 1 << k;
        if (mask === 0 || mask === 15) continue;
        const X = [i, i + 1, i + 1, i], Y = [j, j, j + 1, j + 1];
        const pt = (a, b) => {
          const t = v[a] / (v[a] - v[b]);
          return [(X[a] + (X[b] - X[a]) * t) / nx, (Y[a] + (Y[b] - Y[a]) * t) / ny];
        };
        const cr = [
          (v[0] < 0) !== (v[1] < 0), (v[1] < 0) !== (v[2] < 0),
          (v[2] < 0) !== (v[3] < 0), (v[3] < 0) !== (v[0] < 0),
        ];
        const ncross = cr[0] + cr[1] + cr[2] + cr[3];
        if (ncross === 2) {
          const a = cr.indexOf(true), b = cr.indexOf(true, a + 1);
          const p = pt(a, (a + 1) % 4), q = pt(b, (b + 1) % 4);
          segs.push([p[0], p[1], q[0], q[1]]);
        } else if (ncross === 4) {
          // saddle cell: connect both diagonal pairs
          let p = pt(0, 1), q = pt(2, 3);
          segs.push([p[0], p[1], q[0], q[1]]);
          p = pt(1, 2); q = pt(3, 0);
          segs.push([p[0], p[1], q[0], q[1]]);
        }
      }
    }
    return segs;
  }

  // ---- precompute the truth's and every member's 4 K contour once
  const truthSegs = (() => {
    const f = new Float64Array(nx * ny);
    for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) f[j * nx + i] = truthT[j][i];
    return contourSegs(f);
  })();
  const memberSegs = new Array(nens);
  const memberCentres = new Float64Array(nens * 2);   // normalised 0..1
  {
    const f = new Float64Array(nx * ny);
    for (let m = 0; m < nens; m++) {
      for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) f[j * nx + i] = ensT[j][i][m];
      const segs = contourSegs(f);
      memberSegs[m] = segs;
      let sx = 0, sy = 0, n = 0;
      for (let k = 0; k < segs.length; k++) { sx += segs[k][0] + segs[k][2]; sy += segs[k][1] + segs[k][3]; n += 2; }
      memberCentres[2 * m] = sx / n;
      memberCentres[2 * m + 1] = sy / n;
    }
  }

  // member palette (Tab20-style cycle, same as the position-error widget)
  const MEM_COLORS = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd",
    "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf"];
  const memColor = (m) => MEM_COLORS[m % MEM_COLORS.length];

  // ------------------------------------------------------ canvas utils
  function drawSegs(ctx, W, H, segs, stroke, lw, alpha) {
    if (!segs.length) return;
    ctx.save();
    ctx.globalAlpha = alpha;
    ctx.strokeStyle = stroke;
    ctx.lineWidth = lw;
    ctx.lineJoin = "round";
    ctx.beginPath();
    for (let k = 0; k < segs.length; k++) {
      ctx.moveTo(segs[k][0] * W, segs[k][1] * H);
      ctx.lineTo(segs[k][2] * W, segs[k][3] * H);
    }
    ctx.stroke();
    ctx.restore();
  }
  const ctxNullWarned = new Set();
  function warnCtxNull(id) {
    if (!ctxNullWarned.has(id)) {
      ctxNullWarned.add(id);
      console.warn(`[corr-explorer] canvas "${id}" has no 2d context ` +
        "(device canvas memory limit?) — skipping draw until it recovers");
    }
  }

  function fitCanvas(cv) {
    const rect = cv.getBoundingClientRect();
    // Bail out if the canvas isn't laid out yet (first paint on a phone page,
    // or while the widget is below the fold): drawing into a zero-sized canvas
    // draws everything off-screen and a later redraw fixes it.
    if (!(rect.width > 0.5) || !(rect.height > 0.5)) return null;
    // Cap devicePixelRatio at 2: on high-DPI phones (3x, 3.5x) three canvases
    // each multiplied by dpr can exhaust the WebView's canvas memory, after
    // which getContext("2d") returns null and the panel silently stays blank.
    // 2x is plenty sharp for these line/scatter plots.
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const w = Math.max(1, Math.round(rect.width * dpr));
    const h = Math.max(1, Math.round(rect.height * dpr));
    if (cv.width !== w || cv.height !== h) { cv.width = w; cv.height = h; }
    const ctx = cv.getContext("2d");
    if (!ctx) {                 // context lost / out of memory: skip this frame;
      warnCtxNull(cv.id);       // a later resize/theme render may recover.
      return null;
    }
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, rect.width, rect.height);
    return { ctx, w: rect.width, h: rect.height };
  }

  function drawField(ctx, W, H, field, lo, hi, lutArr) {
    const off = document.createElement("canvas");
    off.width = nx; off.height = ny;
    const octx = off.getContext("2d");
    const img = octx.createImageData(nx, ny);
    const data = img.data;
    for (let j = 0; j < ny; j++) {
      for (let i = 0; i < nx; i++) {
        const t = clamp((field[j][i] - lo) / (hi - lo || 1), 0, 1);
        const c = lutArr[Math.round(t * 255)];
        const p = (j * nx + i) * 4;
        data[p] = c[0]; data[p + 1] = c[1]; data[p + 2] = c[2]; data[p + 3] = 255;
      }
    }
    octx.putImageData(img, 0, 0);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(off, 0, 0, W, H);
  }

  function px(i) { return (i + 0.5) / nx; }   // normalised 0..1
  function py(j) { return (j + 0.5) / ny; }

  function drawMarkers(ctx, W, H) {
    const cx = cssVar("--accent-fill");
    // obs marker: red circle, white face (notebook add_obs_marker)
    const ox = px(obs.i) * W, oy = py(obs.j) * H;
    ctx.beginPath();
    ctx.arc(ox, oy, 7, 0, Math.PI * 2);
    ctx.fillStyle = cx; ctx.fill();
    ctx.lineWidth = 1.75;
    ctx.strokeStyle = cssVar("--series-red");
    ctx.stroke();
    // state marker: black square, white face (notebook add_state_marker)
    const sx = px(si) * W, sy = py(sj) * H, s = 6;
    ctx.fillStyle = cx;
    ctx.fillRect(sx - s, sy - s, s * 2, s * 2);
    ctx.lineWidth = 1.75;
    ctx.strokeStyle = cssVar("--series-ink");
    ctx.strokeRect(sx - s, sy - s, s * 2, s * 2);
  }

  // axis ticks on maps (km, centred on domain, like notebook set_map_axis)
  function drawMapAxis(ctx, W, H) {
    const ink = cssVar("--ink-3");
    ctx.font = "9px system-ui, sans-serif";
    ctx.fillStyle = ink;
    const cticks = [5, 15, 25, 35, 45];
    for (const c of cticks) {
      const xpos = px(c) * W;
      ctx.beginPath();
      ctx.moveTo(xpos, H - 1); ctx.lineTo(xpos, H - 4);
      ctx.strokeStyle = ink; ctx.lineWidth = 1; ctx.stroke();
      const lab = Math.round((xM[c] - D.meta.Lx / 2) / 1e3);
      ctx.textAlign = "center";
      ctx.fillText(lab, xpos, H - 6);
      const ypos = py(c) * H;
      ctx.beginPath();
      ctx.moveTo(0, ypos); ctx.lineTo(4, ypos);
      ctx.strokeStyle = ink; ctx.stroke();
      ctx.textAlign = "left";
      ctx.fillText(Math.round((yM[c] - D.meta.Ly / 2) / 1e3), 6, ypos + 3);
    }
  }

  function drawColorbar(cv, lo, hi, lutArr, seq) {
    const fit = fitCanvas(cv);
    if (!fit) return;
    const { ctx, w, h } = fit;
    // w is the CSS width, which can be fractional (e.g. 268.31 on a high-DPI
    // phone): without clamping, the last iteration reads lut[256] and throws,
    // aborting render() before the scatter panel is ever drawn. Clamp the LUT
    // index to [0,255].
    for (let k = 0; k < w; k++) {
      const c = lutArr[Math.max(0, Math.min(255, Math.round((k / (w - 1)) * 255)))];
      ctx.fillStyle = `rgb(${c[0] | 0},${c[1] | 0},${c[2] | 0})`;
      ctx.fillRect(k, 0, 1, h);
    }
    const lbl = cv.parentElement.querySelector(".cb-labels");
    if (lbl) {
      const f = (x) => (Math.abs(x) < 1e-9 ? "0" : x.toFixed(x < 3 ? 1 : 0));
      lbl.querySelector(".cb-min").textContent = f(lo);
      lbl.querySelector(".cb-mid").textContent = seq ? f((lo + hi) / 2) : "0";
      lbl.querySelector(".cb-max").textContent = f(hi);
    }
  }

  // ------------------------------------------------------------ scatter
  function drawScatter(cv, ensVals, truthVal, r, vname) {
    const fit = fitCanvas(cv);
    if (!fit) return;
    const { ctx, w, h } = fit;
    const mL = SC_M.l, mR = SC_M.r, mT = SC_M.t, mB = SC_M.b;
    const pw = w - mL - mR, ph = h - mT - mB;
    const X = (v) => mL + ((v - S_LO) / (S_HI - S_LO)) * pw;
    const Y = (v) => mT + ((S_HI - v) / (S_HI - S_LO)) * ph;

    // axes + grid (0..10 every 2 K)
    ctx.strokeStyle = cssVar("--line");
    ctx.lineWidth = 1;
    for (const t of [0, 2, 4, 6, 8, 10]) {
      ctx.beginPath(); ctx.moveTo(X(t), mT); ctx.lineTo(X(t), mT + ph); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(mL, Y(t)); ctx.lineTo(mL + pw, Y(t)); ctx.stroke();
    }
    ctx.strokeStyle = cssVar("--axis");
    ctx.strokeRect(mL, mT, pw, ph);

    // tick labels
    ctx.font = "9px system-ui, sans-serif";
    ctx.fillStyle = cssVar("--ink-3");
    ctx.textAlign = "center";
    for (const t of [0, 2, 4, 6, 8, 10]) {
      ctx.fillText(t, X(t), mT + ph + 12);
      ctx.fillText(t, mL - 5, Y(t) + 3);
    }
    ctx.textAlign = "center";
    ctx.fillStyle = cssVar("--ink-2");
    ctx.fillText(`Obs T (K)`, mL + pw / 2, h - 6);
    ctx.save();
    ctx.translate(12, mT + ph / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.fillText(`State T (K)`, 0, 0);
    ctx.restore();

    // ensemble points (aqua) — always shown, independent of the contour toggle;
    // skip any non-finite member so a single bad value can't silently break
    // the rest of the panel
    {
      ctx.fillStyle = cssVar("--series-aqua");
      for (let m = 0; m < nens; m++) {
        const x = X(obsEns[m]), y = Y(ensVals[m]);
        if (!isFinite(x) || !isFinite(y)) continue;
        ctx.globalAlpha = 0.75;
        ctx.beginPath();
        ctx.arc(x, y, 2.4, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.globalAlpha = 1;
    }

    // observation value line (amber) at x = obs.val
    ctx.strokeStyle = cssVar("--series-amber");
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(X(obs.val), mT);
    ctx.lineTo(X(obs.val), mT + ph);
    ctx.stroke();

    // truth value line (ink) at y = truth at (i,j)
    ctx.strokeStyle = cssVar("--series-ink");
    ctx.lineWidth = 1.25;
    ctx.beginPath();
    ctx.moveTo(mL, Y(truthVal));
    ctx.lineTo(mL + pw, Y(truthVal));
    ctx.stroke();

    // selected member: ringed + filled in its contour colour, so the slider
    // choice is visible in the joint distribution too
    const sxp = X(obsEns[sel]), syp = Y(ensVals[sel]);
    if (isFinite(sxp) && isFinite(syp)) {
      ctx.beginPath();
      ctx.arc(sxp, syp, 5, 0, Math.PI * 2);
      ctx.lineWidth = 2;
      ctx.strokeStyle = memColor(sel);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(sxp, syp, 2.6, 0, Math.PI * 2);
      ctx.fillStyle = memColor(sel);
      ctx.fill();
    }
  }

  // ------------------------------------------------------------- render
  function render() {
    // re-build LUT for current theme
    const stops = LUT_STOPS[theme];
    const l2 = makeLUT(stops, divMap);
    lut.splice(0, lut.length, ...l2);
    const th2 = makeLUT(LUT_THERMAL[theme], seqMap);
    lutTh.splice(0, lutTh.length, ...th2);

    // truth map (sequential YlOrRd, 0..vmax + 4 K contours) /
    // covariance map (diverging, -covmax..covmax)
    drawTruthMap($("map-truth"));
    drawMap($("map-cov"), covT, -covmax, covmax, lut);
    drawColorbar($("cb-truth"), 0, vmax, lutTh, true);
    drawColorbar($("cb-cov"), -covmax, covmax, lut, false);

    // scatter panel
    let r = corrT[sj][si];
    if (!isFinite(r)) r = 0;      // defensive: a degenerate correlation (0/0)
                                  // would otherwise print "r = NaN"
    let cov = covT[sj][si];
    if (!isFinite(cov)) cov = 0;
    const ensVals = ensT[sj][si];
    drawScatter($("scat"), ensVals || [], truthT[sj][si], r, "T");
    $("t-scat").textContent = "cov = " + cov.toFixed(2) + " K² (r = " + r.toFixed(2) + ")";

    const sgn = (x) => (Math.abs(x) < 0.5 ? "0" : (x > 0 ? "+" : "−") + Math.abs(x).toFixed(0));
    const dx = (memberCentres[2 * sel] - 0.5) * LKM;
    const dy = (memberCentres[2 * sel + 1] - 0.5) * LKM;
    $("readout").innerHTML =
      `State <strong>(i, j) = (${si}, ${sj})</strong> · ` +
      `truth T = <strong>${truthT[sj][si].toFixed(1)}</strong> K · ` +
      `cov(obs T, state T) = <strong>${cov.toFixed(2)}</strong> K&sup2; ` +
      `= &sigma;<sub>obs</sub>&sigma;<sub>state</sub>&rho; = ${stdObs.toFixed(2)} &times; ${stdState[sj][si].toFixed(2)} &times; ${r.toFixed(2)}<br>` +
      `member <strong>${sel + 1}</strong> · blob centre <strong>(${sgn(dx)}, ${sgn(dy)}) km</strong> from truth · ` +
      `T(m) at (i, j) = <strong>${(ensVals[sel] || 0).toFixed(1)}</strong> K`;
  }

  // truth panel: field + every member's 4 K contour + selected member +
  // truth ring (halo + ink core) + markers + axis
  function drawTruthMap(cv) {
    const fit = fitCanvas(cv);
    if (!fit) return;
    const { ctx, w, h } = fit;
    drawField(ctx, w, h, truthT, 0, vmax, lutTh);
    if (showContours) {
      for (let m = 0; m < nens; m++) {
        if (m === sel) continue;
        drawSegs(ctx, w, h, memberSegs[m], memColor(m), 1, 0.45);
      }
    }
    // selected member: thick ring + blob centre dot
    drawSegs(ctx, w, h, memberSegs[sel], memColor(sel), 2.4, 1);
    const cxm = memberCentres[2 * sel] * w, cym = memberCentres[2 * sel + 1] * h;
    ctx.beginPath();
    ctx.arc(cxm, cym, 4.5, 0, Math.PI * 2);
    ctx.fillStyle = cssVar("--accent-fill");
    ctx.fill();
    ctx.lineWidth = 1.6;
    ctx.strokeStyle = memColor(sel);
    ctx.stroke();
    // truth 4 K contour: halo + ink core so it reads on every colour
    drawSegs(ctx, w, h, truthSegs, theme === "dark" ? "#241439" : "#ffffff", 3.4, 0.95);
    drawSegs(ctx, w, h, truthSegs, cssVar("--series-ink"), 1.6, 1);
    drawMarkers(ctx, w, h);
    drawMapAxis(ctx, w, h);
  }

  function drawMap(cv, field, lo, hi, lutArr) {
    const fit = fitCanvas(cv);
    if (!fit) return;
    drawField(fit.ctx, fit.w, fit.h, field, lo, hi, lutArr);
    drawMarkers(fit.ctx, fit.w, fit.h);
    drawMapAxis(fit.ctx, fit.w, fit.h);
  }

  // --------------------------------------------------------- interaction
  function mapPosToIJ(cv, clientX, clientY) {
    const rect = cv.getBoundingClientRect();
    const fx = clamp((clientX - rect.left) / rect.width, 0, 1);
    const fy = clamp((clientY - rect.top) / rect.height, 0, 1);
    return { i: Math.floor(fx * nx), j: Math.floor(fy * ny) };
  }

  function setMarker(i, j, doRender) {
    si = clamp(Math.round(i), 0, kx);
    sj = clamp(Math.round(j), 0, ky);
    if (doRender !== false) render();
  }

  // click / drag on any map to move the state marker
  for (const id of ["map-truth", "map-cov"]) {
    const cv = $(id);
    let dragging = false;
    const move = (e) => {
      const { i, j } = mapPosToIJ(cv, e.clientX, e.clientY);
      if (dragging || e.type === "click") setMarker(i, j, true);
    };
    cv.addEventListener("pointerdown", (e) => {
      dragging = true;
      move(e);
      try { cv.setPointerCapture(e.pointerId); } catch (err) { /* touch on some iOS versions */ }
    });
    cv.addEventListener("pointermove", (e) => { if (dragging) move(e); });
    cv.addEventListener("pointerup", () => { dragging = false; hideTooltip(); });
    // belt-and-braces: stop the browser from turning a touch drag on the maps
    // into a page scroll (in addition to touch-action:none in the CSS)
    cv.addEventListener("touchstart", (e) => e.preventDefault(), { passive: false });
    // hover tooltip (mouse only — on touch it would linger after the drag)
    cv.addEventListener("pointermove", (e) => {
      if (e.pointerType !== "mouse") return;
      const { i, j } = mapPosToIJ(cv, e.clientX, e.clientY);
      showTooltip(e.clientX, e.clientY, i, j);
    });
    cv.addEventListener("pointerleave", hideTooltip);
  }

  // tooltip: value at the hovered cell
  let tip = document.createElement("div");
  tip.id = "tooltip";
  (root || document.body).appendChild(tip);
  function showTooltip(cx, cy, i, j) {
    tip.innerHTML =
      `<strong>(${i}, ${j})</strong>` +
      ` · T = ${truthT[j][i].toFixed(2)} K` +
      ` · cov = ${covT[j][i].toFixed(2)} K²`;
    tip.style.display = "block";
    const pad = 14;
    let lx = cx + pad, ly = cy + pad;
    if (lx + 240 > window.innerWidth) lx = cx - 260;
    if (ly + 30 > window.innerHeight) ly = cy - 40;
    tip.style.left = lx + "px";
    tip.style.top = ly + "px";
  }
  function hideTooltip() { tip.style.display = "none"; }

  // ----------------------------------------------------------------- init
  const nensEl = $("nens-label");   // optional: shown in the standalone hero tag
  if (nensEl) nensEl.textContent = nens;

  // select a member (click a scatter dot) — highlights its 4 K contour
  // (truth panel), its blob centre and its ringed point in the scatter
  function setSel(m) {
    sel = clamp(m, 0, nens - 1);
    render();
  }
  // click on the scatter to select the nearest member
  const scatCv = $("scat");
  if (scatCv) {
    scatCv.addEventListener("click", (e) => {
      const rect = scatCv.getBoundingClientRect();
      const cx = e.clientX - rect.left, cy = e.clientY - rect.top;
      const pw = rect.width - SC_M.l - SC_M.r, ph = rect.height - SC_M.t - SC_M.b;
      if (pw <= 0 || ph <= 0) return;
      const X = (v) => SC_M.l + ((v - S_LO) / (S_HI - S_LO)) * pw;
      const Y = (v) => SC_M.t + ((S_HI - v) / (S_HI - S_LO)) * ph;
      const ensVals = ensT[sj][si];
      if (!ensVals) return;
      let best = -1, bd = 25 * 25;          // click within 25 CSS px of a dot
      for (let m = 0; m < nens; m++) {
        const x = X(obsEns[m]), y = Y(ensVals[m]);
        if (!isFinite(x) || !isFinite(y)) continue;
        const dx = x - cx, dy = y - cy, d2 = dx * dx + dy * dy;
        if (d2 < bd) { bd = d2; best = m; }
      }
      if (best >= 0) setSel(best);
    });
  }
  const membersEl = $("cont-members");
  if (membersEl) {
    membersEl.checked = showContours;
    membersEl.addEventListener("change", () => {
      showContours = membersEl.checked;
      render();
    });
  }
  window.addEventListener("resize", () => render());
  // Re-render when the embedded widget's box changes size (e.g. the site page
  // reflows while fonts/images load); a no-op in the standalone layout.
  if (window.ResizeObserver) {
    const ro = new ResizeObserver(() => render());
    ro.observe(root);
    // Also observe each canvas: a phone browser may lay the canvases out only
    // after the first render (below-the-fold first paint), and only a size
    // change on the canvas itself reliably triggers the redraw.
    for (const id of ["map-truth", "map-cov", "scat"]) ro.observe($(id));
  }
  // On some mobile browsers the first render can run before the stylesheet
  // layout settles (canvases still 0-sized); try again once more on the next
  // frame and after load so the plot isn't left blank.
  requestAnimationFrame(render);
  if (document.readyState !== "complete") addEventListener("load", render);
  setTheme(theme);   // sets data-theme + first render
})();
